import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // The firewall, made structural.
  //
  // Verification has to produce the same answers with the operator's service dead — that property is
  // the product, and it survives only as long as no code path under lib/verify can reach operator
  // infrastructure, even by accident, even through a type import. So the boundary is not a convention
  // and not a habit of code review: a build that crosses it does not compile.
  {
    files: ["lib/verify/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/relayer", "**/relayer/**", "@/lib/relayer", "@/lib/relayer/**"],
              message:
                "lib/verify must never import the operator's client. If the page can only verify while " +
                "Good is alive, the kill switch is a lie. Read the chain or public storage instead.",
            },
          ],
        },
      ],
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // A projection of the contracts, generated by scripts/sync-artifacts.mjs.
    "lib/chain/generated/**",
  ]),
]);

export default eslintConfig;
